# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [ ]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [ ]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [ ]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [ ]:
# Інспектування массива
np.info(arr)

In [ ]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

In [ ]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

In [ ]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

In [ ]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

In [ ]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

In [ ]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

In [ ]:
arr.__sizeof__()

### ЗАВДАННЯ 1

In [2]:
import numpy as np
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.array([[1.0, 2.0, 3.0, 4.0], 
                   [5.0, 6.0, 7.0, 8.0], 
                   [9.0, 10.0, 11.0, 12.0]])
print(arr1_1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [3]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(["Яблуко", "Банан", "Вишня", "Полуниця", "Кавун"])
print(arr1_2)

['Яблуко' 'Банан' 'Вишня' 'Полуниця' 'Кавун']


In [4]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3, 4), dtype=float)
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [ ]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

In [ ]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

In [ ]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

In [ ]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

### ЗАВДАННЯ 2

In [5]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.zeros((3, 1, 3), dtype=bool)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [11]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.astype(int)
print(arr2_2)

[[[0 0 0]]

 [[0 0 0]]

 [[0 0 0]]]


In [12]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 22, 2).reshape(2, 3)
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [ ]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

In [13]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[10 25 42 46]
 [30 32 13 46]
 [11 23 22 26]
 [48 40 16 24]]


In [ ]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

In [ ]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

In [ ]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

In [ ]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

In [ ]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

In [ ]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

### ЗАВДАННЯ 3

In [14]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
np.random.seed(42)
arr3_1 = np.random.normal(55, 15, size=(4, 5))
arr3_1 = np.round(arr3_1)
arr3_1 = np.where(arr3_1 < 10, 10, arr3_1)
arr3_1 = np.where(arr3_1 > 100, 100, arr3_1)
print(arr3_1)

[[62. 53. 65. 78. 51.]
 [51. 79. 67. 48. 63.]
 [48. 48. 59. 26. 29.]
 [47. 40. 60. 41. 34.]]


In [15]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1][2]
print(el3_2)

67.0


In [16]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[51. 79. 67. 48. 63.]


In [17]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[65. 67. 59. 60.]


In [18]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[79. 67.]
 [48. 59.]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [ ]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

In [ ]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

In [ ]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

In [ ]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

In [ ]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

In [ ]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

### ЗАВАДАННЯ 4

In [19]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100, 201, size=(6, 6))
print(mat4_1)

[[161 161 146 161 150 154]
 [163 102 200 150 106 120]
 [172 138 117 103 188 159]
 [113 108 189 152 101 183]
 [191 159 170 143 107 146]
 [134 177 180 135 149 103]]


In [20]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[161 102 117 152 107 103]


In [21]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[161 163 172 113 191 134]
 [161 102 138 108 159 177]
 [146 200 117 189 170 180]
 [161 150 103 152 143 135]
 [150 106 188 101 107 149]
 [154 120 159 183 146 103]]


In [22]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[-0.00186145  0.00607098  0.00293643 -0.00782193  0.00846831 -0.00692919]
 [-0.00216046 -0.01364422 -0.00379628  0.001073    0.01020379  0.00861664]
 [-0.01620779  0.00380159  0.00173246  0.00483021  0.0005659   0.0077456 ]
 [ 0.02710875  0.00750205 -0.01106002 -0.00512901 -0.01128148 -0.00709461]
 [ 0.0025491   0.00550607  0.00709477 -0.00259219 -0.01373575  0.00289739]
 [-0.0047598  -0.00889273  0.00390873  0.01036341  0.00511591 -0.00451241]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [ ]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [ ]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

In [ ]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

In [ ]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

In [ ]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

In [ ]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

In [ ]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

In [ ]:
# поелементний поділ
K = N / M
print(K)

In [ ]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

In [ ]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

In [ ]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

In [ ]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

In [ ]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

In [ ]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

In [ ]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

### ЗАВДАННЯ 5

In [23]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(0, 10, size=(3, 4))
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[20 18 20]


In [24]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = np.min(mat5_1)
print(min_mat5_1)

1


In [25]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[101 105 105 109]
 [103 105 101 109]
 [101 109 103 107]]


In [31]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_1 = np.random.randint(0, 10, size=(3, 3))
diag = np.diag(np.random.randint(0, 2, size=3))
mat5_4 = np.dot(mat5_1, diag)
print(mat5_4)

[[2 0 4]
 [9 6 9]
 [8 6 8]]


In [37]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
print(mat5_5)
print(np.linalg.matrix_rank(mat5_5))

[[101 105 105 109   2   0   4]
 [103 105 101 109   9   6   9]
 [101 109 103 107   8   6   8]]
3
